"""empty message

Revision ID: 40fef5aedb7c
Revises: 693a41594fb7
Create Date: 2024-04-05 03:33:11.614883

"""

# revision identifiers, used by Alembic.
revision = '40fef5aedb7c'
down_revision = '693a41594fb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
