"""Add major column

Revision ID: 693a41594fb7
Revises: 794f44029982
Create Date: 2024-04-05 03:19:10.596385

"""

# revision identifiers, used by Alembic.
revision = '693a41594fb7'
down_revision = '794f44029982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
